[versions]
minecraft = "26.1"
compatibility = "26.1.x"
fabric-api = "0.155.2+26.1.2"

caxton = "paJOxYlD"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

caxton = { module = "maven.modrinth:caxton", version.ref = "caxton" }
