[versions]
minecraft = "26.2"
compatibility = "26.2.x"
fabric-api = "0.158.0+26.2"

caxton = "wVI9Rvrv"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

caxton = { module = "maven.modrinth:caxton", version.ref = "caxton" }
