[versions]
minecraft = "26.3-rc-2"
compatibility = "26.3.x"
fabric-api = "0.160.4+26.3"

caxton = "lOy6RSRI"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

caxton = { module = "maven.modrinth:caxton", version.ref = "caxton" }
