[versions]
loom = "1.17-SNAPSHOT"
kotlin = "2.4.10"

devauth = "1.2.2"
kommand = "1.0.1"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

fabric-api-26-1 = "0.155.2+26.1.2"
fabric-api-26-2 = "0.158.0+26.2"

caxton-26-1 = "paJOxYlD"
caxton-26-2 = "wVI9Rvrv"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }

caxton-26-1 = { module = "maven.modrinth:caxton", version.ref = "caxton-26-1" }
caxton-26-2 = { module = "maven.modrinth:caxton", version.ref = "caxton-26-2" }

fabric-api-26-1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-1" }
fabric-api-26-2 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
