[versions]
loom = "1.17-SNAPSHOT"
kotlin = "2.4.10"

devauth = "1.2.2"
kommand = "1.0.2"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
